/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JethroLeroux;

import java.io.*;


/**
 *
 * @author Jethro
 */
public class AddUser extends javax.swing.JFrame {

    /**
     * Creates new form AddUser
     */
    public AddUser() { //constructor method of the JFrame, initializes components
        initComponents();
        javax.swing.ImageIcon pic = new javax.swing.ImageIcon("background.jpg");    //loads in the background image
        javax.swing.ImageIcon scaledPic = new javax.swing.ImageIcon(pic.getImage().getScaledInstance(510, 360, 0));//resizes the image to the JFrames dimensions
        lblBackground.setIcon(scaledPic);//sets the background labels icon as the image
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblSurname = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        lblAuthenticity = new javax.swing.JLabel();
        lblInitial = new javax.swing.JLabel();
        labelNB = new javax.swing.JLabel();
        txfAuthenticity = new javax.swing.JTextField();
        txfInitial = new javax.swing.JTextField();
        txfSurname = new javax.swing.JTextField();
        txfPassword = new javax.swing.JTextField();
        btnAddUser = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Aharoni", 0, 36)); // NOI18N
        lblTitle.setText("Add User:");
        getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 180, 70));

        lblSurname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblSurname.setText("Surname:");
        getContentPane().add(lblSurname, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        lblPassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPassword.setText("Password:");
        getContentPane().add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        lblAuthenticity.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblAuthenticity.setText("Authenticity Number:");
        getContentPane().add(lblAuthenticity, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        lblInitial.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblInitial.setText("First Initial:");
        getContentPane().add(lblInitial, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        labelNB.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelNB.setText("NB: An admin - 1, an employee - 0");
        getContentPane().add(labelNB, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, -1, -1));
        getContentPane().add(txfAuthenticity, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 230, 30));

        txfInitial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfInitialActionPerformed(evt);
            }
        });
        getContentPane().add(txfInitial, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 230, 30));
        getContentPane().add(txfSurname, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 230, 30));
        getContentPane().add(txfPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 230, 30));

        btnAddUser.setText("Add User");
        btnAddUser.setAutoscrolls(true);
        btnAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddUserActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 330, -1, -1));

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JethroLeroux/background.jpg"))); // NOI18N
        getContentPane().add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txfInitialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfInitialActionPerformed

    }//GEN-LAST:event_txfInitialActionPerformed

    private void btnAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddUserActionPerformed
        Writer output;  //creates a new Writer object for writing to the text file
        try{
            output = new BufferedWriter(new FileWriter("LoginDetails.txt",true)); //new buffered writer and file writer for appending to the text file. Note: true makes the File Writer only add new text instead of replacing all the text
            output.append(System.getProperty("line.separator"));//starts the new users details on a new line
            output.append(txfInitial.getText().toLowerCase() + txfSurname.getText().toLowerCase() + "#" + txfPassword.getText() + "#" + txfAuthenticity.getText()); //gets the users data from the text fields and formats it
            output.close(); //closes the Writer object
            txfInitial.setText("");txfSurname.setText("");txfPassword.setText("");txfAuthenticity.setText("");//sets the text in the text fields to null/empties the fields
            ActionPerformed ap = new ActionPerformed();//shows the user an action has been performed
            ap.setVisible(true);
        }catch(IOException e){System.out.println("File not found" + e);} //catch file not found error
    }//GEN-LAST:event_btnAddUserActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.setVisible(false);       
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddUser;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel labelNB;
    private javax.swing.JLabel lblAuthenticity;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblInitial;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblSurname;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txfAuthenticity;
    private javax.swing.JTextField txfInitial;
    private javax.swing.JTextField txfPassword;
    private javax.swing.JTextField txfSurname;
    // End of variables declaration//GEN-END:variables
}
