/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JethroLeroux;

import java.io.*;
import java.util.*;

/**
 *
 * @author Jethro
 */
public class DeleteUser extends javax.swing.JFrame {

    /**
     * Creates new form DeleteUser
     */
    public DeleteUser() {
        initComponents();  //initialize components in the JFrame
        javax.swing.ImageIcon pic = new javax.swing.ImageIcon("background.jpg"); //load in the background image
        javax.swing.ImageIcon scaledPic = new javax.swing.ImageIcon(pic.getImage().getScaledInstance(510, 360, 0));//resize the image
        lblBackground.setIcon(scaledPic); //set the labels icon to the image
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        txfUsername = new javax.swing.JTextField();
        cbDelete = new javax.swing.JCheckBox();
        btnBack = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        labelNB = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Aharoni", 0, 36)); // NOI18N
        lblTitle.setText("Delete User:");
        getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 220, 70));

        lblUsername.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblUsername.setText("Username:");
        getContentPane().add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));

        txfUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfUsernameActionPerformed(evt);
            }
        });
        getContentPane().add(txfUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 230, 30));

        cbDelete.setText("Are you sure you want to delete this user?");
        getContentPane().add(cbDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, -1, -1));

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        btnDelete.setText("Delete User");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, -1, -1));

        labelNB.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelNB.setText("NB: Username = First Name Initial + Surname");
        getContentPane().add(labelNB, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 280, -1));

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JethroLeroux/background.jpg"))); // NOI18N
        getContentPane().add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txfUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfUsernameActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
       this.setVisible(false);  //close this screen/Jframe
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        if(cbDelete.isSelected())   //only if the user has selelcted the checkbox
        {
            String out = "";
        
            try{
            Scanner sc = new Scanner(new FileReader("LoginDetails.txt"));   //accesses the text file
            while(sc.hasNext())
            {
                String line = sc.nextLine();        //splits the text file into a line at a time
                String[]temp =line.split("#");      //splits each line into the parts separated by #'s
                
                if(!txfUsername.getText().equals(temp[0]))  //if the username the admin wants to delete is NOT the same as the username which has been found
                {
                     out = out+line+ System.getProperty("line.separator");  //then put that line in the output string variable. Line separator system property creates a line break
                }
            }
            Writer output = new BufferedWriter(new FileWriter("LoginDetails.txt")); //Writer object to write to the text file LoginDetails.txt
            output.append(out); //edit the text file by inserting all the records which WERENT the user to be deleted
            output.close(); //close the object
            ActionPerformed ap = new ActionPerformed(); //load action performed screen to show the User the deletion has been performed
            ap.setVisible(true);
            }catch(IOException e){System.out.println("File not found" + e); //IO (file not found) error catch
        }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JCheckBox cbDelete;
    private javax.swing.JLabel labelNB;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JTextField txfUsername;
    // End of variables declaration//GEN-END:variables
}
