/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JethroLeroux;

/**
 *
 * @author Jethro
 */
public class EditScreen extends javax.swing.JFrame {
    private boolean admin = false;//user is not an admin by default
    /**
     * Creates new form EditScreen
     */
    public EditScreen(boolean authorisation) {
        initComponents();   //initialize the JFrames components
        javax.swing.ImageIcon pic = new javax.swing.ImageIcon("background.jpg");//load in the background image
        javax.swing.ImageIcon scaledPic = new javax.swing.ImageIcon(pic.getImage().getScaledInstance(500, 330, 0));//resize the image
        lblBackground.setIcon(scaledPic);//set the labels icon as the image
        admin =authorisation;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lblTitle = new javax.swing.JLabel();
        radbtnCars = new javax.swing.JRadioButton();
        radbtnCustomers = new javax.swing.JRadioButton();
        radbtnEmployees = new javax.swing.JRadioButton();
        radbtnRepairs = new javax.swing.JRadioButton();
        radbtnPayments = new javax.swing.JRadioButton();
        lblNew = new javax.swing.JLabel();
        txfKeyField = new javax.swing.JTextField();
        lblKeyField = new javax.swing.JLabel();
        txfNew = new javax.swing.JTextField();
        lblUpdateField = new javax.swing.JLabel();
        txfUpdateField = new javax.swing.JTextField();
        btnEdit = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        lblExplain1 = new javax.swing.JLabel();
        lblExplain2 = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Aharoni", 0, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("Edit Item");
        getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        radbtnCars.setText("Cars");
        radbtnCars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radbtnCarsActionPerformed(evt);
            }
        });
        getContentPane().add(radbtnCars, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        radbtnCustomers.setText("Customers");
        radbtnCustomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radbtnCustomersActionPerformed(evt);
            }
        });
        getContentPane().add(radbtnCustomers, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        radbtnEmployees.setText(" Employees");
        radbtnEmployees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radbtnEmployeesActionPerformed(evt);
            }
        });
        getContentPane().add(radbtnEmployees, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 90, -1));

        radbtnRepairs.setText("Repairs");
        radbtnRepairs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radbtnRepairsActionPerformed(evt);
            }
        });
        getContentPane().add(radbtnRepairs, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, -1, -1));

        radbtnPayments.setText("Payments");
        radbtnPayments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radbtnPaymentsActionPerformed(evt);
            }
        });
        getContentPane().add(radbtnPayments, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, -1, -1));

        lblNew.setBackground(new java.awt.Color(255, 255, 255));
        lblNew.setForeground(new java.awt.Color(255, 255, 255));
        lblNew.setText("New value for field:");
        getContentPane().add(lblNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, 20));
        getContentPane().add(txfKeyField, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 130, 30));

        lblKeyField.setBackground(new java.awt.Color(255, 255, 255));
        lblKeyField.setForeground(new java.awt.Color(255, 255, 255));
        lblKeyField.setText("Primary key ID value  :");
        getContentPane().add(lblKeyField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 114, -1, -1));
        getContentPane().add(txfNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 130, 30));

        lblUpdateField.setBackground(new java.awt.Color(255, 255, 255));
        lblUpdateField.setForeground(new java.awt.Color(255, 255, 255));
        lblUpdateField.setText("Field to be updated (Eg. CarID, Model, etc) : ");
        getContentPane().add(lblUpdateField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, 20));
        getContentPane().add(txfUpdateField, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 130, 30));

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        getContentPane().add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 80, 30));

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 80, 30));

        lblExplain1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblExplain1.setForeground(new java.awt.Color(255, 255, 255));
        lblExplain1.setText("true/false for boolean fields");
        getContentPane().add(lblExplain1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 210, 20));

        lblExplain2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblExplain2.setForeground(new java.awt.Color(255, 255, 255));
        lblExplain2.setText("Read from table columns NB: Case Sensitive!");
        getContentPane().add(lblExplain2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 210, 20));

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JethroLeroux/background.jpg"))); // NOI18N
        getContentPane().add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 400, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radbtnCarsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radbtnCarsActionPerformed
        radbtnCustomers.setSelected(false);     //code to make the other radio buttons unchecked when this one is checked so only one table can be deleted from at a time
        radbtnEmployees.setSelected(false);
        radbtnPayments.setSelected(false);
        radbtnRepairs.setSelected(false);
    }//GEN-LAST:event_radbtnCarsActionPerformed

    private void radbtnCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radbtnCustomersActionPerformed
        radbtnCars.setSelected(false);     //code to make the other radio buttons unchecked when this one is checked so only one table can be deleted from at a time
        radbtnEmployees.setSelected(false);
        radbtnPayments.setSelected(false);
        radbtnRepairs.setSelected(false);
    }//GEN-LAST:event_radbtnCustomersActionPerformed

    private void radbtnEmployeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radbtnEmployeesActionPerformed
        radbtnCars.setSelected(false);     //code to make the other radio buttons unchecked when this one is checked so only one table can be deleted from at a time
        radbtnCustomers.setSelected(false);
        radbtnPayments.setSelected(false);
        radbtnRepairs.setSelected(false);
    }//GEN-LAST:event_radbtnEmployeesActionPerformed

    private void radbtnPaymentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radbtnPaymentsActionPerformed
        radbtnCars.setSelected(false);     //code to make the other radio buttons unchecked when this one is checked so only one table can be deleted from at a time
        radbtnCustomers.setSelected(false);
        radbtnEmployees.setSelected(false);
        radbtnRepairs.setSelected(false);
    }//GEN-LAST:event_radbtnPaymentsActionPerformed

    private void radbtnRepairsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radbtnRepairsActionPerformed
        radbtnCars.setSelected(false);     //code to make the other radio buttons unchecked when this one is checked so only one table can be deleted from at a time
        radbtnCustomers.setSelected(false);
        radbtnEmployees.setSelected(false);
        radbtnPayments.setSelected(false);
    }//GEN-LAST:event_radbtnRepairsActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
         boolean performed = false; //boolean variable to say if a delete function has been performed
        
        if(radbtnCars.isSelected()) //when the Cars radio button is checked
        {
            CarDBM c = new CarDBM(); //create an object of manager class
            c.editCar(Integer.parseInt(txfKeyField.getText()), txfUpdateField.getText(), txfNew.getText());    //calls the delete method in the manager class which has the Delete SQL Query in it
            performed=true; //edit has been performed
        }else
            if(radbtnCustomers.isSelected())    //when the Customers radio button is checked
                {
                    CustomerDBM c = new CustomerDBM(); //create an object of manager class
                    c.editCustomer(Integer.parseInt(txfKeyField.getText()), txfUpdateField.getText(), txfNew.getText());    //calls the delete method in the manager class which has the Delete SQL Query in it
                    performed=true; //edit has been performed
                }else
                    if(radbtnEmployees.isSelected())    //when the Employees radio button is checked
                    {
                        if(admin) //only an admin can delete from the payments/employees table
                        {
                            EmployeeDBM c = new EmployeeDBM(); //create an object of manager class
                            c.editEmployee(Integer.parseInt(txfKeyField.getText()), txfUpdateField.getText(), txfNew.getText());    //calls the delete method in the manager class which has the Delete SQL Query in it
                            performed=true; //edit has been performed
                        }else //user is not an admin
                            {
                                AuthorisationError ae = new AuthorisationError(); //explains why access has been denied
                                ae.setVisible(true);
                            }
                    }else
                        if(radbtnRepairs.isSelected())  //when the Repairs radio button is checked
                        {
                            RepairDBM c = new RepairDBM(); //create an object of manager class
                            c.editRepair(Integer.parseInt(txfKeyField.getText()), txfUpdateField.getText(), txfNew.getText());    //calls the delete method in the manager class which has the Delete SQL Query in it
                            performed=true; //edit has been performed
                        }else
                             if(radbtnPayments.isSelected())    //when the Payments radio button is checked
                                {
                                    if(admin) //only an admin can delete from the payments/employees table
                                    {
                                        PaymentDBM c = new PaymentDBM(); //create an object of manager class
                                        c.editPayment(Integer.parseInt(txfKeyField.getText()), txfUpdateField.getText(), txfNew.getText());    //calls the delete method in the manager class which has the Delete SQL Query in it
                                        performed=true; //edit has been performed
                                    }else //user is not an admin
                                        {
                                            AuthorisationError ae = new AuthorisationError(); //explains why access has been denied
                                            ae.setVisible(true);
                                        }
                                }else
                                    System.out.println("No table has been selected! Please select a table by checking a radio button."); //data validation to check a table has been chosen
                
        
        if(performed)//if a deletion has been performed
        {
            ActionPerformed ap = new ActionPerformed(); //loads action performed screen to show user a deletion has occurred
            ap.setVisible(true);
            
            txfKeyField.setText("");             //clear every text field and radio button to be ready for the user to start the next edit
            txfNew.setText("");
            txfUpdateField.setText("");
            radbtnPayments.setSelected(false);     
            radbtnCars.setSelected(false);
            radbtnEmployees.setSelected(false);
            radbtnRepairs.setSelected(false);
            radbtnCustomers.setSelected(false);
        } //there doesnt have to be an else as the DBM method already tells the user if the deletion failed
   
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.setVisible(false); //closes this JFrame
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EditScreen es = new EditScreen(false);  //user is not admin by default
                es.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnEdit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblExplain1;
    private javax.swing.JLabel lblExplain2;
    private javax.swing.JLabel lblKeyField;
    private javax.swing.JLabel lblNew;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUpdateField;
    private javax.swing.JRadioButton radbtnCars;
    private javax.swing.JRadioButton radbtnCustomers;
    private javax.swing.JRadioButton radbtnEmployees;
    private javax.swing.JRadioButton radbtnPayments;
    private javax.swing.JRadioButton radbtnRepairs;
    private javax.swing.JTextField txfKeyField;
    private javax.swing.JTextField txfNew;
    private javax.swing.JTextField txfUpdateField;
    // End of variables declaration//GEN-END:variables
}
