/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JethroLeroux;

/**
 *
 * @author Jethro
 */
public class HelpScreen extends javax.swing.JFrame {

    /**
     * Creates new form HelpScreen
     */
    public HelpScreen() {
        initComponents();
        javax.swing.ImageIcon pic = new javax.swing.ImageIcon("logo.png");//load in the background image
        javax.swing.ImageIcon scaledPic = new javax.swing.ImageIcon(pic.getImage().getScaledInstance(460,323, 0));//resize the image
        lblBackground.setIcon(scaledPic); //set the labels icon as the image
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHelpScreen = new javax.swing.JLabel();
        lblHelp = new javax.swing.JLabel();
        lblExample = new javax.swing.JLabel();
        lblFurtherHelp = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHelpScreen.setFont(new java.awt.Font("BankGothic Md BT", 1, 36)); // NOI18N
        lblHelpScreen.setText("Help Screen");
        getContentPane().add(lblHelpScreen, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 300, 50));

        lblHelp.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblHelp.setText("Username = first name initial + last name. All in lower case.");
        getContentPane().add(lblHelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 340, 60));

        lblExample.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblExample.setText("Example. Jethro Leroux = 'jleroux'");
        getContentPane().add(lblExample, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, -1, 20));

        lblFurtherHelp.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        lblFurtherHelp.setText("Speak to the manager about forgotten passwords. Visit the PDF document for further help");
        getContentPane().add(lblFurtherHelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 450, 30));

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, 70, -1));

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JethroLeroux/Logo.png"))); // NOI18N
        getContentPane().add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HelpScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HelpScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HelpScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HelpScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HelpScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblExample;
    private javax.swing.JLabel lblFurtherHelp;
    private javax.swing.JLabel lblHelp;
    private javax.swing.JLabel lblHelpScreen;
    // End of variables declaration//GEN-END:variables
}
