/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JethroLeroux;

/**
 *
 * @author Jethro
 */
public class IncomeSummary extends javax.swing.JFrame { /*NOTE:
                                                        Had to take the month and year buttons out 
                                                        because there is no date field for when an 
                                                        item is payed for*/
    PaymentDBM pdbm = new PaymentDBM();

    /**
     * Creates new form IncomeSummary
     */
    public IncomeSummary() {
        initComponents();   //initializes components of the JFrame
        javax.swing.ImageIcon pic = new javax.swing.ImageIcon("background.jpg");//loads background image
        javax.swing.ImageIcon scaledPic = new javax.swing.ImageIcon(pic.getImage().getScaledInstance(510, 360, 0));//resizes image to JFrames dimensions
        btnGetIncome.setIcon(scaledPic);//makes the labels icon the resized image
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnMonth = new javax.swing.JButton();
        txfIncome = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        btnGetIncome = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Aharoni", 0, 36)); // NOI18N
        lblTitle.setText("Total income:");
        getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 230, 80));

        btnMonth.setText("Get All Income");
        btnMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMonthActionPerformed(evt);
            }
        });
        getContentPane().add(btnMonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 140, 30));
        getContentPane().add(txfIncome, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 100, 40));

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 70, 30));

        btnGetIncome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JethroLeroux/background.jpg"))); // NOI18N
        getContentPane().add(btnGetIncome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.setVisible(false);        //close this JFrame
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMonthActionPerformed

        PaymentObject[] payments =  pdbm.getPayments();
        int monthIncome = 0;

        for (int i = 0; i<pdbm.getArrLength(); i++) {
            if(payments[i].isPaid())//only if the fee has been paid for, therefore it is income for the business
            {
                monthIncome = monthIncome + payments[i].getFee(); //insert this objects paid fee into the total income
            }
        }
        txfIncome.setText("R" + monthIncome);

    }//GEN-LAST:event_btnMonthActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IncomeSummary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IncomeSummary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IncomeSummary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IncomeSummary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IncomeSummary().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel btnGetIncome;
    private javax.swing.JButton btnMonth;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txfIncome;
    // End of variables declaration//GEN-END:variables
}
