/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JethroLeroux;

/**
 *
 * @author Jethro
 */
public class OverallStats extends javax.swing.JFrame {
    PaymentDBM pdbm = new PaymentDBM();
    /**
     * Creates new form OverallStats
     */
    public OverallStats() {
        initComponents();   //initializes the JFrames components
        javax.swing.ImageIcon pic = new javax.swing.ImageIcon("background.jpg");//loads in the background image
        javax.swing.ImageIcon scaledPic = new javax.swing.ImageIcon(pic.getImage().getScaledInstance(510, 360, 0));//resizes the image
        lblBackground.setIcon(scaledPic);//sets the background labels icon as the resized image
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSearch = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        btnShowStats = new javax.swing.JButton();
        lblMin = new javax.swing.JLabel();
        txfAvg = new javax.swing.JTextField();
        lblMax = new javax.swing.JLabel();
        txfMax = new javax.swing.JTextField();
        lblAvg = new javax.swing.JLabel();
        txfMin = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        lblBackground = new javax.swing.JLabel();

        btnSearch.setText("Search");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Aharoni", 0, 36)); // NOI18N
        lblTitle.setText("Overall Stats:");
        getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 260, 100));

        btnShowStats.setText("Show Stats");
        btnShowStats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowStatsActionPerformed(evt);
            }
        });
        getContentPane().add(btnShowStats, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, -1, -1));

        lblMin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblMin.setText("Min fee payed:");
        getContentPane().add(lblMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 170, 30));
        getContentPane().add(txfAvg, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 170, 30));

        lblMax.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblMax.setText("Max fee payed:");
        getContentPane().add(lblMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 170, 30));
        getContentPane().add(txfMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 170, 30));

        lblAvg.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblAvg.setText("Average fee payed:");
        getContentPane().add(lblAvg, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 170, 30));
        getContentPane().add(txfMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 170, 30));

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JethroLeroux/background.jpg"))); // NOI18N
        getContentPane().add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
     this.setVisible(false);//closes this JFrame
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnShowStatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowStatsActionPerformed
       //fill the text fields with calculated data from the payments table
        String stats = pdbm.getOverallStats();
        String[] temp =  stats.split("#");//splits up received string of payment values
        txfMax.setText("R" + temp[0]);//display the max fee paid
        txfMin.setText("R" + temp[1]);//display the min fee paid
        txfAvg.setText("R" + temp[2]);//display the avg fee paid
    }//GEN-LAST:event_btnShowStatsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OverallStats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OverallStats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OverallStats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OverallStats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OverallStats().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnShowStats;
    private javax.swing.JLabel lblAvg;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblMax;
    private javax.swing.JLabel lblMin;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txfAvg;
    private javax.swing.JTextField txfMax;
    private javax.swing.JTextField txfMin;
    // End of variables declaration//GEN-END:variables
}
