/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JethroLeroux;

/**
 *
 * @author Jethro
 */
public class SpecificStats extends javax.swing.JFrame {
PaymentDBM pdbm = new PaymentDBM();
    /**
     * Creates new form SpecificStats
     */
    public SpecificStats() {
       initComponents();//initiialize the JFrames components
        javax.swing.ImageIcon pic = new javax.swing.ImageIcon("background.jpg");//load in the background image
        javax.swing.ImageIcon scaledPic = new javax.swing.ImageIcon(pic.getImage().getScaledInstance(510, 360, 0));//resize the image to the JFrames dimensions
        lblBackground.setIcon(scaledPic);//set the background labels icon as the resized image
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        txfCarID = new javax.swing.JTextField();
        lblIncome = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        lblCarID = new javax.swing.JLabel();
        lblTimesVisited = new javax.swing.JLabel();
        txfTimesVisited = new javax.swing.JTextField();
        txfIncome = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Aharoni", 0, 36)); // NOI18N
        lblTitle.setText("Specific Statistics of a vehicle:");
        getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 110));
        getContentPane().add(txfCarID, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 200, 30));

        lblIncome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblIncome.setText("Income from this car:");
        getContentPane().add(lblIncome, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 180, 30));

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, -1, -1));

        lblCarID.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblCarID.setText("Car ID:");
        getContentPane().add(lblCarID, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 80, 30));

        lblTimesVisited.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTimesVisited.setText("No. of times Visited:");
        getContentPane().add(lblTimesVisited, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 170, 30));
        getContentPane().add(txfTimesVisited, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 170, 30));
        getContentPane().add(txfIncome, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 170, 30));

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JethroLeroux/background.jpg"))); // NOI18N
        getContentPane().add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
       this.setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String stats = pdbm.getSpecificStats();
        String[] temp =  stats.split("#");//splits up received string of payment values
        txfTimesVisited.setText("" + temp[0]);//display the number of times this car has come to the repair shop
        txfIncome.setText("R" + temp[1]);//display the total income received from repairs on this car
    }//GEN-LAST:event_btnSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SpecificStats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SpecificStats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SpecificStats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SpecificStats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SpecificStats().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblCarID;
    private javax.swing.JLabel lblIncome;
    private javax.swing.JLabel lblTimesVisited;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txfCarID;
    private javax.swing.JTextField txfIncome;
    private javax.swing.JTextField txfTimesVisited;
    // End of variables declaration//GEN-END:variables
}
